-- migrate:up

-- Insert sample companies for development/testing
-- Note: UUIDs will be auto-generated by the database
INSERT INTO companies (name, subscription_plan) VALUES
    ('Acme Corporation', 'enterprise'),
    ('TechStart Inc', 'premium'),
    ('Digital Solutions Ltd', 'basic'),
    ('Innovation Labs', 'premium'),
    ('Global Enterprises', 'enterprise'),
    ('StartupCo', 'basic'),
    ('Enterprise Solutions', 'enterprise'),
    ('Cloud Services Ltd', 'premium'),
    ('Data Analytics Inc', 'basic'),
    ('AI Innovations', 'premium');

-- migrate:down

-- Remove seed data (optional - keeps data by default)
-- Uncomment the lines below if you want seed data to be removed on rollback
-- DELETE FROM companies WHERE name IN (
--     'Acme Corporation',
--     'TechStart Inc', 
--     'Digital Solutions Ltd',
--     'Innovation Labs',
--     'Global Enterprises',
--     'StartupCo',
--     'Enterprise Solutions',
--     'Cloud Services Ltd',
--     'Data Analytics Inc',
--     'AI Innovations'
-- );