version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: saas-postgres
    environment:
      POSTGRES_DB: saas_microcourses
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d saas_microcourses"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas-app
    environment:
      DATABASE_URL: postgres://admin:password@postgres:5432/saas_microcourses?sslmode=disable
      PORT: 50051
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - saas-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  saas-network:
    driver: bridge