// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID               pgtype.UUID      `json:"id"`
	Name             pgtype.Text      `json:"name"`
	SubscriptionPlan pgtype.Text      `json:"subscription_plan"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Auth0ID   string           `json:"auth0_id"`
	Email     string           `json:"email"`
	Name      pgtype.Text      `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
