// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID               pgtype.UUID        `json:"id"`
	Name             pgtype.Text        `json:"name"`
	SubscriptionPlan pgtype.Text        `json:"subscription_plan"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
