// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCompanies(ctx context.Context) (int64, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	DeleteCompany(ctx context.Context, id pgtype.UUID) error
	GetCompany(ctx context.Context, id pgtype.UUID) (Company, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
}

var _ Querier = (*Queries)(nil)
